- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "removing lock file"
  become: true
  command: rm /var/lib/dpkg/lock-frontend

- name: "Install NodeJS"
  become: true
  apt:
    name: ["nodejs"]
    state: latest

- name: "Create directory for backend app"
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "Copy files to backend folder"
  become: true
  copy:
      src: ~/project/artifact.tar.gz
      dest: /home/ubuntu/backend/artifact.tar.gz
      backup: yes

- name: Extract artifact files
  become: true
  shell: |
    cd /home/ubuntu/backend
    tar -xvf artifact.tar.gz

- name: "Install NPM"
  become: true
  apt:
    name: ["npm"]
    state: latest

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "start pm2"
  become: true
  command: pm2 start npm

- name: "Starts Web Server"
  shell: |
      cd /home/ubuntu/backend 
      pm2 npm start