- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes
    
- name: "removing lock file"
  become: true
  command: rm /var/lib/dpkg/lock-frontend

- name: "Install Python"
  become: true
  raw: apt -y install python3

- name: "Install NodeJS"
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "Install NPM"
  become: true
  apt:
    name: ["npm"]
    state: latest
    update_cache: yes

- name: "Extract artifact into EC2"
  ansible.builtin.unarchive:
    src: ~/project/backend/artifact.tar.gz
    dest: .
    remote_src: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "start pm2"
  become: true
  command: pm2 start npm