- name: Update APT Cache
  become: true
  apt:
    update_cache: yes
    force_apt_get: yes

- name: Remove apt lock file
  become: true
  file:
    state: absent
    path: "/var/lib/dpkg/lock"

- name: Upgrade all packages to the latest version
  become: true
  apt:
    name: "*"
    state: latest
    force_apt_get: yes

- name: "removing lock file"
  become: true
  command: rm /var/lib/dpkg/lock-frontend

- name: "removing lock file"
  become: true
  command: rm /var/lib/dpkg/lock

- name: "removing lock file"
  become: true
  command: rm /var/lib/apt/lists/lock

- name: "removing lock file"
  become: true
  command: rm /var/cache/apt/archives/lock

- name: "Install NodeJS"
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "Install NPM"
  become: true
  apt:
    name: ["npm"]
    state: latest
    update_cache: yes

- name: "Extract artifact into EC2"
  ansible.builtin.unarchive:
    src: ~/project/backend/artifact.tar.gz
    dest: .
    remote_src: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "start pm2"
  become: true
  command: pm2 start npm